# Generated by Django 4.2.1 on 2023-05-09 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couriers',
            options={'ordering': ['id', 'courier_type', 'regions', 'working_hours'], 'verbose_name_plural': 'Couriers'},
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('regions', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('completed_time', models.CharField(default=None)),
                ('courier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.couriers')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['id', 'weight', 'regions', 'cost', 'completed_time', 'courier'],
            },
        ),
    ]
