# Generated by Django 4.2.1 on 2023-05-09 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orders_completed_time_alter_orders_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), default=['08:00-12:00', '14:00-16:00'], size=None),
            preserve_default=False,
        ),
    ]
