# Generated by Django 4.2.1 on 2023-05-13 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orders_complete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='assignment_date',
            field=models.DateField(default=datetime.date(2023, 5, 13)),
        ),
    ]
